### ISSUE TITLE
browserify build steps

### ISSUE THREAD

**Issue by waldenn** [tom-s/select-and-speak#1]
Hi Tom,

Thanks for this interesting project. Could you explain how you build the browserify bundle for ES2015 systems?

I tried building my own browserify bundle by creating a new npm project, and listing "select-and-speak" in the dependencies, then running browserify on the index.js (containing the demo code listed on you project page). The bundle builds fine, but its not functional (the Speech object is available, but its functions are not resolved). It seems I am doing this browserify thing somewhat wrong.

**Comment by tom-s** [comment]
Hi,

I build the dist with webpack and babel. I don't have experience with browserify, I'm afraid I can't help you on that front :-(

**Comment by waldenn** [comment]
Ok thanks, I will use babel instead (just tried and that works fine).
